name: OpenMod.Rocket.PermissionLink

on:
  create:
    tags:
      - "*"
  push:
    branches: [ master ]
    paths:
      - 'unturned/rocketmod/Rocket.PermissionLink/**'        
  pull_request:
    branches: [ master ]
    paths:
      - 'unturned/rocketmod/Rocket.PermissionLink/**' 

jobs:
  build:
    name: "OpenMod.Rocket.PermissionLink Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Extract version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --tags)        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore unturned/rocketmod/Rocket.PermissionLink
    - name: Update version
      run: "sed -i \"s#0.0.0#${{ steps.get_version.outputs.VERSION }}#\" unturned/rocketmod/props/SharedProjectProps.props"
    - name: Build
      run: dotnet build unturned/rocketmod/Rocket.PermissionLink --configuration Release --no-restore
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
    - name: Push to NuGet
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: dotnet nuget push unturned/rocketmod/Rocket.PermissionLink/bin/Release/*.nupkg
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source https://api.nuget.org/v3/index.json