name: OpenMod.Unturned.Module

on:
  release:
    types: [published]
  push:
    branches: [ master ]
    paths:
      - 'framework/**'
      - 'unityengine/**'      
      - 'unturned/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'framework/**'
      - 'unityengine/**'      
      - 'unturned/**'

jobs:
  build:
    name: "OpenMod.Unturned.Module Build"
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Extract version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --tags)     
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Update version
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ steps.get_version.outputs.VERSION }}</Version>#\" props/SharedProjectProps.props"  
    - name: Build
      run: dotnet build unturned/OpenMod.Unturned.Module --configuration Release --no-restore
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
    - name: Get Release
      if: github.event_name == 'release'
      id: get-release
      uses: bruceadams/get-release@v1.2.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Install zip
      if: github.event_name == 'release'
      run: sudo apt-get install zip
    - name: Zip artifacts
      if: github.event_name == 'release'
      run: "mkdir ./release && mkdir ./release/OpenMod.Unturned/ && mv ./unturned/OpenMod.Unturned.Module/bin/Release/net461/* ./release/OpenMod.Unturned/ && mv ./release/OpenMod.Unturned/Readme.txt ./release && cd ./release && zip -qq -r ./release.zip *"
    - name: Upload release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.get-release.outputs.upload_url }}
        asset_path: ./release/release.zip
        asset_name: OpenMod.Unturned.Module-v${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip