name: OpenMod.UniTask

on:
  create:
    tags:
      - "*"
  push:
    branches: [ master ]
    paths:
      - 'unityengine/UniTask/**'        
  pull_request:
    branches: [ master ]
    paths:
      - 'unityengine/UniTask/**' 

jobs:
  build:
    name: "OpenMod.UniTask Pack"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - uses: nuget/setup-nuget@v1
      name: Setup NuGet
      with:
        nuget-api-key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget-version: '5.x'       
    - name: Pack
      run: nuget pack unityengine/UniTask/OpenMod.UniTask.nuspec
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
    - name: Push to NuGet
      run: dotnet nuget push *.nupkg
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source https://api.nuget.org/v3/index.json